version: "3.9"

services:
  nextjs-grpc-infra-config-app-security:
    container_name: nextjs-grpc-infra-config-app-security
    image: utkusarioglu/tf-k8s-devcontainer:1.2.18
    environment:
      TZ: Etc/UTC0
      TARGET_VOLUMES_ROOT: /var/lib/rancher/k3s/storage
      CLUSTER_REGION: eu-central-1
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/projects/nextjs-grpc/infra/configs/app/security
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
